name: Update v1 tag on release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-v1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Move v1 tag to this release
        run: |
          git fetch --tags
          COMMIT_SHA=$(git rev-list -n 1 ${{ github.event.release.tag_name }})
          echo "Release tag '${{ github.event.release.tag_name }}' resolves to commit $COMMIT_SHA"
          git tag -f v1 $COMMIT_SHA
          git push origin -f v1
